import { useState, useRef } from 'react';
import { jsPDF } from 'jspdf';
import { Download, FileText, RotateCcw } from 'lucide-react';

export default function PdfGenerator() {
  const [title, setTitle] = useState('Sample Document');
  const [subtitle, setSubtitle] = useState('Generated by DocForge');
  const [content, setContent] = useState(
    'This is a sample PDF document generated entirely in your browser using the DocForge toolkit.\n\nYou can use this tool to create invoices, reports, certificates, labels, and any other document you need.\n\nAll processing happens locally — no data is sent to any external server.\n\nFeatures:\n• Custom page sizes\n• Headers and footers\n• Multiple font styles\n• Tables and formatting\n• Page numbering'
  );
  const [pageSize, setPageSize] = useState<'a4' | 'letter' | 'legal'>('a4');
  const [fontSize, setFontSize] = useState(12);
  const [includeHeader, setIncludeHeader] = useState(true);
  const [includePageNumbers, setIncludePageNumbers] = useState(true);
  const [generating, setGenerating] = useState(false);

  const generatePdf = () => {
    setGenerating(true);
    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: pageSize,
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;
      let y = margin;

      // Header
      if (includeHeader) {
        doc.setFillColor(16, 185, 129);
        doc.rect(0, 0, pageWidth, 35, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.text(title, margin, 18);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.text(subtitle, margin, 27);
        y = 45;
      }

      // Body content
      doc.setTextColor(30, 30, 30);
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', 'normal');

      const lines = doc.splitTextToSize(content, contentWidth);
      const lineHeight = fontSize * 0.45;

      for (let i = 0; i < lines.length; i++) {
        if (y + lineHeight > pageHeight - margin) {
          doc.addPage();
          y = margin;
        }
        doc.text(lines[i], margin, y);
        y += lineHeight;
      }

      // Page numbers
      if (includePageNumbers) {
        const totalPages = doc.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          doc.setPage(i);
          doc.setFontSize(9);
          doc.setTextColor(150, 150, 150);
          doc.text(
            `Page ${i} of ${totalPages}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
          );
        }
      }

      doc.save(`${title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
    } catch (err) {
      console.error(err);
      alert('Error generating PDF: ' + (err as Error).message);
    }
    setGenerating(false);
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
        <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
          <FileText className="w-5 h-5 text-emerald-400" />
          PDF Generator
        </h3>
        <p className="text-sm text-gray-400 mb-6">
          Create professional PDF documents with custom content, headers, and page settings.
        </p>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Settings */}
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-300 mb-1">Document Title</label>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full px-3 py-2 rounded-lg bg-gray-800 border border-gray-700 text-white text-sm focus:outline-none focus:border-emerald-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-300 mb-1">Subtitle</label>
              <input
                type="text"
                value={subtitle}
                onChange={(e) => setSubtitle(e.target.value)}
                className="w-full px-3 py-2 rounded-lg bg-gray-800 border border-gray-700 text-white text-sm focus:outline-none focus:border-emerald-500"
              />
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1">Page Size</label>
                <select
                  value={pageSize}
                  onChange={(e) => setPageSize(e.target.value as any)}
                  className="w-full px-3 py-2 rounded-lg bg-gray-800 border border-gray-700 text-white text-sm focus:outline-none focus:border-emerald-500"
                >
                  <option value="a4">A4</option>
                  <option value="letter">Letter</option>
                  <option value="legal">Legal</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1">Font Size</label>
                <select
                  value={fontSize}
                  onChange={(e) => setFontSize(Number(e.target.value))}
                  className="w-full px-3 py-2 rounded-lg bg-gray-800 border border-gray-700 text-white text-sm focus:outline-none focus:border-emerald-500"
                >
                  <option value={10}>10pt</option>
                  <option value={11}>11pt</option>
                  <option value={12}>12pt</option>
                  <option value={14}>14pt</option>
                  <option value={16}>16pt</option>
                </select>
              </div>
            </div>

            <div className="flex items-center gap-4">
              <label className="flex items-center gap-2 text-sm text-gray-300 cursor-pointer">
                <input
                  type="checkbox"
                  checked={includeHeader}
                  onChange={(e) => setIncludeHeader(e.target.checked)}
                  className="rounded bg-gray-800 border-gray-700 text-emerald-500 focus:ring-emerald-500"
                />
                Include Header
              </label>
              <label className="flex items-center gap-2 text-sm text-gray-300 cursor-pointer">
                <input
                  type="checkbox"
                  checked={includePageNumbers}
                  onChange={(e) => setIncludePageNumbers(e.target.checked)}
                  className="rounded bg-gray-800 border-gray-700 text-emerald-500 focus:ring-emerald-500"
                />
                Page Numbers
              </label>
            </div>

            <div className="flex gap-3 pt-2">
              <button
                onClick={generatePdf}
                disabled={generating}
                className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-emerald-500 hover:bg-emerald-600 text-white font-medium text-sm transition-colors disabled:opacity-50"
              >
                <Download className="w-4 h-4" />
                {generating ? 'Generating...' : 'Generate & Download PDF'}
              </button>
              <button
                onClick={() => {
                  setTitle('Sample Document');
                  setSubtitle('Generated by DocForge');
                  setContent('Enter your document content here...');
                }}
                className="flex items-center gap-2 px-4 py-2.5 rounded-lg bg-gray-800 hover:bg-gray-700 text-gray-300 text-sm transition-colors"
              >
                <RotateCcw className="w-4 h-4" />
                Reset
              </button>
            </div>
          </div>

          {/* Content editor */}
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-1">Document Content</label>
            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              rows={16}
              className="w-full px-3 py-2 rounded-lg bg-gray-800 border border-gray-700 text-white text-sm font-mono focus:outline-none focus:border-emerald-500 resize-none"
              placeholder="Enter your document text here..."
            />
          </div>
        </div>
      </div>
    </div>
  );
}
